Autodetect toolbox refactor in tsx
Outlook-Suzhou/autodetect-toolbox-tsx pull request #1
Opened 2021-07-08 07:28 UTC by Park-J-lab

AAD login is under debugging, other parts are good to go.

2021-07-09 11:12 UTC, Wanjing-Li commented on react-seed/src/components/Body.tsx
> +import "../styles/antd.css";
What's the main purpose to import `antd.css` twice? 
Followed this [doc](https://ant.design/docs/react/use-with-create-react-app) to import it correctly.

2021-07-09 11:12 UTC, Wanjing-Li commented on react-seed/package.json
> +  "name": "react-seed",
The root dir name  `react-seed` doesn't make sense to me.

2021-07-12 05:01 UTC, haven2world commented on react-seed/package.json
> +  "name": "react-seed",
I think it'd be better to move everything in `react-seed` to the root dir

2021-07-12 10:08 UTC, haven2world commented on react-seed/src/components/Response.tsx
> +    <div className="JSONResponse">
How about JSON-response

2021-07-12 10:08 UTC, haven2world commented on react-seed/src/components/SearchBox.tsx
> +import "../styles/App.css";
I think they only need to be imported once in `App.tsx`. Does it work?

2021-07-12 10:08 UTC, haven2world commented on react-seed/src/pages/Home/AutoDetect.tsx
> +    const res = http.get<AxiosResponse>(
Could we move this to Service.ts?

2021-07-12 10:08 UTC, haven2world commented on react-seed/src/pages/Home/AutoDiscoverExo.tsx
> +    const res = http.get<AxiosResponse>(
ditto

2021-07-12 10:08 UTC, haven2world commented on react-seed/src/pages/Home/Home.css
> +  font-size: calc(10px + 2vmin);
Why we use this font size?

2021-07-12 10:08 UTC, haven2world commented on react-seed/src/pages/Home/Home.test.tsx
> +import React from 'react';
Could we removed this file?

2021-07-12 10:08 UTC, haven2world commented on react-seed/src/pages/Login/Login.tsx
> +          style={{
Let's move all styles in this file to a css file

2021-07-12 13:55 UTC, schuberng requested changes
Please resolve all comments before merge this PR.

2021-07-12 13:55 UTC, schuberng commented on react-seed/src/mock/fetchWfhStatusMock.ts
> +export const fetchWfhStatusMock = [{
I don't think this Mock file is used in our project, is it?

2021-07-12 13:55 UTC, schuberng commented on react-seed/src/util/authConfig.ts
> +            console.error(message);
Do we need console.log to find error info?

2021-07-12 13:55 UTC, schuberng commented on react-seed/src/util/utils.ts
> +    console.error(e);
same here

2021-07-12 14:04 UTC, schuberng requested changes

2021-07-13 03:34 UTC, Wanjing-Li commented on react-seed/src/Router.tsx
> +export const RootRouter = (): JSX.Element => (
Can  you change the return type as `React.FC<props>`?

2021-07-13 03:34 UTC, Wanjing-Li commented on react-seed/src/components/Menu.tsx
> +    <Menu.Item key="0">Loading</Menu.Item>
What's the difference between `ContentMenu` and `LodingMenu`?  Can you pass these parameters as config and use `Factory Pattern` to generate the menu?

2021-07-13 03:34 UTC, Wanjing-Li commented on react-seed/src/components/RequestDisplayer.tsx
> +  requestResponse: service.FetchWfhStatusRes;
Define this as a type Props?

2021-07-13 03:34 UTC, Wanjing-Li commented on react-seed/src/components/Response.tsx
> +import "../styles/App.css";
`App.css` has been imported into `App.tsx`

2021-07-13 03:34 UTC, Wanjing-Li commented on react-seed/src/components/SearchBox.tsx
> +  onSubmit = (e: { preventDefault: () => void }): void => {
I think the type of `e` shouldn't be this. How about `React.xxxEvent<xxxElement>`?

2021-07-13 03:34 UTC, Wanjing-Li commented on react-seed/src/components/SearchBox.tsx
> +  onChange = (e: { target: { name: string; value: string } }): void => {
same here

2021-07-13 03:34 UTC, Wanjing-Li commented on react-seed/src/components/SearchBox.tsx
> +          className="Searchbar"
camel-case?

2021-07-13 03:34 UTC, Wanjing-Li commented on react-seed/src/components/SignOutButton.tsx
> +export const SignOutButton = () => {
The DOM structure of `sign in` and `sign out` looks the same, merge them into one component?

2021-07-13 03:34 UTC, Wanjing-Li commented on react-seed/src/pages/Home/AutoDetect.tsx
> +export class Autodetect extends Component<PageProps, PageState> {
Merge AutoDetect and AutoDiscoverExo and AutoDiscoverOnPrem and FetchEas and SovereignDiscover?

2021-07-13 03:34 UTC, Wanjing-Li commented on react-seed/src/styles/App.css
> +  padding: 1rem 1.25rem;
Why your css rules contain relative and absolute units ? `px, em, vh, vmin, %`

2021-07-13 06:45 UTC, Park-J-lab commented on react-seed/package.json
> +  "name": "react-seed",
Resolved.

2021-07-13 10:33 UTC, Park-J-lab commented on react-seed/src/Router.tsx
> +    <Route path="/autodetect" exact component={Autodetect} />
Modified.

2021-07-13 10:33 UTC, Park-J-lab commented on react-seed/src/components/Body.tsx
> +    console.log(collapsed);
Removed.

2021-07-13 10:43 UTC, Park-J-lab commented on react-seed/src/components/Body.tsx
> +              <a href="/autodetect">AutoDetect</a>
Thanks, I have replaced.

2021-07-13 10:46 UTC, Park-J-lab commented on react-seed/src/components/Navbar.tsx
> +      <Col span={1} style={{ marginLeft: "6%" }}>
The purpose is just to place this element in a proper position to make the whole part coordinated.

2021-07-13 10:47 UTC, Park-J-lab commented on react-seed/src/components/Navbar.tsx
> +          <div className="myitem-1" style={{ marginLeft: "1800%" }}>
Removed.

2021-07-13 10:50 UTC, Park-J-lab commented on react-seed/src/components/ProfileContent.tsx
> +    <div style={{ marginTop: "-5%" }}>
Removed.

2021-07-13 10:50 UTC, Park-J-lab commented on react-seed/src/components/Response.tsx
> +    <div className="JSONResponse">
Good idea.

2021-07-13 11:09 UTC, Park-J-lab commented on react-seed/src/pages/Home/AutoDetect.tsx
> +    const res = http.get<AxiosResponse>(
Good idea. Resolved.

2021-07-13 11:09 UTC, Park-J-lab commented on react-seed/src/pages/Home/AutoDiscoverExo.tsx
> +    const res = http.get<AxiosResponse>(
Resolved.

2021-07-14 02:24 UTC, closed without merging

2021-07-14 02:26 UTC, Park-J-lab commented on react-seed/src/util/authConfig.ts
> +            console.error(message);
Removed.

2021-07-14 02:30 UTC, Park-J-lab commented on react-seed/src/components/RequestDisplayer.tsx
> +  requestResponse: service.FetchWfhStatusRes;
Removed this file.

2021-07-14 03:33 UTC, Park-J-lab commented on react-seed/src/pages/Home/AutoDetect.tsx
> +export class Autodetect extends Component<PageProps, PageState> {
I extracted some public components.

2021-07-15 07:54 UTC, Park-J-lab commented on react-seed/src/components/Body.tsx
> +import "../styles/antd.css";
resolved

2021-07-15 07:55 UTC, Park-J-lab commented on react-seed/src/components/Menu.tsx
> +    <Menu.Item key="0">Loading</Menu.Item>
The loadingmenu is quite different from contentmenu.

2021-07-15 07:55 UTC, Park-J-lab commented on react-seed/src/components/Response.tsx
> +import "../styles/App.css";
Resolved.

2021-07-15 07:55 UTC, Park-J-lab commented on react-seed/src/components/SearchBox.tsx
> +          className="Searchbar"
Resolved.

2021-07-15 07:58 UTC, Park-J-lab commented on react-seed/src/pages/Home/Home.css
> +  font-size: calc(10px + 2vmin);
Removed.

2021-07-15 07:59 UTC, Park-J-lab commented on react-seed/src/components/SignOutButton.tsx
> +export const SignOutButton = () => {
Good idea, but it is not easy to merge.

2021-07-15 07:59 UTC, Park-J-lab commented on react-seed/src/styles/App.css
> +  padding: 1rem 1.25rem;
This is for specific appearance.